[[rules]]
name="Src"
pattern="^fnl/(.*)%.fnl$"

[[rules.links]]
name="Spec"
pattern="spec/%s_spec.fnl"

[[rules]]
name="Spec"
pattern="^spec/(.*)_spec%.fnl$"

[[rules.links]]
name="Src"
pattern="fnl/%s.fnl"
